package com.immfly.backend.ms.flight.domain.entity;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;


class FlightInformationTest {

  @Test
  void testIdAutoGenerated_success() {
    FlightInformation flightInformation = FlightInformation.builder().build();
    assertNotNull(flightInformation.getIdent());
  }

}
